# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from edgeshard.protocol.pb import shard_runtime_pb2 as shard__runtime__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shard_runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShardRuntimeStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRuntimeInfo = channel.unary_unary(
                '/edgeshard.proto.ShardRuntime/GetRuntimeInfo',
                request_serializer=shard__runtime__pb2.RuntimeInfoRequest.SerializeToString,
                response_deserializer=shard__runtime__pb2.RuntimeInfoReply.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/edgeshard.proto.ShardRuntime/CreateSession',
                request_serializer=shard__runtime__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=shard__runtime__pb2.CreateSessionReply.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/edgeshard.proto.ShardRuntime/CloseSession',
                request_serializer=shard__runtime__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=shard__runtime__pb2.CloseSessionReply.FromString,
                _registered_method=True)
        self.Prefill = channel.unary_unary(
                '/edgeshard.proto.ShardRuntime/Prefill',
                request_serializer=shard__runtime__pb2.ForwardRequest.SerializeToString,
                response_deserializer=shard__runtime__pb2.ForwardReply.FromString,
                _registered_method=True)
        self.Decode = channel.unary_unary(
                '/edgeshard.proto.ShardRuntime/Decode',
                request_serializer=shard__runtime__pb2.ForwardRequest.SerializeToString,
                response_deserializer=shard__runtime__pb2.ForwardReply.FromString,
                _registered_method=True)


class ShardRuntimeServicer:
    """Missing associated documentation comment in .proto file."""

    def GetRuntimeInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prefill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShardRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRuntimeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeInfo,
                    request_deserializer=shard__runtime__pb2.RuntimeInfoRequest.FromString,
                    response_serializer=shard__runtime__pb2.RuntimeInfoReply.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=shard__runtime__pb2.CreateSessionRequest.FromString,
                    response_serializer=shard__runtime__pb2.CreateSessionReply.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=shard__runtime__pb2.CloseSessionRequest.FromString,
                    response_serializer=shard__runtime__pb2.CloseSessionReply.SerializeToString,
            ),
            'Prefill': grpc.unary_unary_rpc_method_handler(
                    servicer.Prefill,
                    request_deserializer=shard__runtime__pb2.ForwardRequest.FromString,
                    response_serializer=shard__runtime__pb2.ForwardReply.SerializeToString,
            ),
            'Decode': grpc.unary_unary_rpc_method_handler(
                    servicer.Decode,
                    request_deserializer=shard__runtime__pb2.ForwardRequest.FromString,
                    response_serializer=shard__runtime__pb2.ForwardReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edgeshard.proto.ShardRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edgeshard.proto.ShardRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShardRuntime:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRuntimeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.proto.ShardRuntime/GetRuntimeInfo',
            shard__runtime__pb2.RuntimeInfoRequest.SerializeToString,
            shard__runtime__pb2.RuntimeInfoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.proto.ShardRuntime/CreateSession',
            shard__runtime__pb2.CreateSessionRequest.SerializeToString,
            shard__runtime__pb2.CreateSessionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.proto.ShardRuntime/CloseSession',
            shard__runtime__pb2.CloseSessionRequest.SerializeToString,
            shard__runtime__pb2.CloseSessionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Prefill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.proto.ShardRuntime/Prefill',
            shard__runtime__pb2.ForwardRequest.SerializeToString,
            shard__runtime__pb2.ForwardReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Decode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.proto.ShardRuntime/Decode',
            shard__runtime__pb2.ForwardRequest.SerializeToString,
            shard__runtime__pb2.ForwardReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
