# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from edgeshard.protocol.control.pb import worker_control_pb2 as worker__control__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in worker_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerRegistryServiceStub:
    """---------------------------------------------------------------------------
    Service (spec 28)
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/edgeshard.control.v1.WorkerRegistryService/RegisterWorker',
                request_serializer=worker__control__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=worker__control__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/edgeshard.control.v1.WorkerRegistryService/Heartbeat',
                request_serializer=worker__control__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=worker__control__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.UpdateCapability = channel.unary_unary(
                '/edgeshard.control.v1.WorkerRegistryService/UpdateCapability',
                request_serializer=worker__control__pb2.UpdateCapabilityRequest.SerializeToString,
                response_deserializer=worker__control__pb2.UpdateCapabilityResponse.FromString,
                _registered_method=True)


class WorkerRegistryServiceServicer:
    """---------------------------------------------------------------------------
    Service (spec 28)
    ---------------------------------------------------------------------------

    """

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCapability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerRegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=worker__control__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=worker__control__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=worker__control__pb2.HeartbeatRequest.FromString,
                    response_serializer=worker__control__pb2.HeartbeatResponse.SerializeToString,
            ),
            'UpdateCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCapability,
                    request_deserializer=worker__control__pb2.UpdateCapabilityRequest.FromString,
                    response_serializer=worker__control__pb2.UpdateCapabilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edgeshard.control.v1.WorkerRegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edgeshard.control.v1.WorkerRegistryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerRegistryService:
    """---------------------------------------------------------------------------
    Service (spec 28)
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.control.v1.WorkerRegistryService/RegisterWorker',
            worker__control__pb2.RegisterWorkerRequest.SerializeToString,
            worker__control__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.control.v1.WorkerRegistryService/Heartbeat',
            worker__control__pb2.HeartbeatRequest.SerializeToString,
            worker__control__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.control.v1.WorkerRegistryService/UpdateCapability',
            worker__control__pb2.UpdateCapabilityRequest.SerializeToString,
            worker__control__pb2.UpdateCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
