# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from edgeshard.protocol.profiling.pb import profiling_pb2 as profiling__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in profiling_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerProfilingServiceStub:
    """---------------------------------------------------------------------------
    Services (§41, §49)
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrepareProfilingSession = channel.unary_unary(
                '/edgeshard.profiling.v1.WorkerProfilingService/PrepareProfilingSession',
                request_serializer=profiling__pb2.PrepareProfilingSessionRequest.SerializeToString,
                response_deserializer=profiling__pb2.PrepareProfilingSessionResponse.FromString,
                _registered_method=True)
        self.RunProfilingCase = channel.unary_unary(
                '/edgeshard.profiling.v1.WorkerProfilingService/RunProfilingCase',
                request_serializer=profiling__pb2.RunProfilingCaseRequest.SerializeToString,
                response_deserializer=profiling__pb2.RunProfilingCaseResponse.FromString,
                _registered_method=True)
        self.GetProfilingCase = channel.unary_unary(
                '/edgeshard.profiling.v1.WorkerProfilingService/GetProfilingCase',
                request_serializer=profiling__pb2.GetProfilingCaseRequest.SerializeToString,
                response_deserializer=profiling__pb2.GetProfilingCaseResponse.FromString,
                _registered_method=True)
        self.CancelProfilingCase = channel.unary_unary(
                '/edgeshard.profiling.v1.WorkerProfilingService/CancelProfilingCase',
                request_serializer=profiling__pb2.CancelProfilingCaseRequest.SerializeToString,
                response_deserializer=profiling__pb2.CancelProfilingCaseResponse.FromString,
                _registered_method=True)
        self.CloseProfilingSession = channel.unary_unary(
                '/edgeshard.profiling.v1.WorkerProfilingService/CloseProfilingSession',
                request_serializer=profiling__pb2.CloseProfilingSessionRequest.SerializeToString,
                response_deserializer=profiling__pb2.CloseProfilingSessionResponse.FromString,
                _registered_method=True)


class WorkerProfilingServiceServicer:
    """---------------------------------------------------------------------------
    Services (§41, §49)
    ---------------------------------------------------------------------------

    """

    def PrepareProfilingSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunProfilingCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfilingCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelProfilingCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseProfilingSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerProfilingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrepareProfilingSession': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareProfilingSession,
                    request_deserializer=profiling__pb2.PrepareProfilingSessionRequest.FromString,
                    response_serializer=profiling__pb2.PrepareProfilingSessionResponse.SerializeToString,
            ),
            'RunProfilingCase': grpc.unary_unary_rpc_method_handler(
                    servicer.RunProfilingCase,
                    request_deserializer=profiling__pb2.RunProfilingCaseRequest.FromString,
                    response_serializer=profiling__pb2.RunProfilingCaseResponse.SerializeToString,
            ),
            'GetProfilingCase': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfilingCase,
                    request_deserializer=profiling__pb2.GetProfilingCaseRequest.FromString,
                    response_serializer=profiling__pb2.GetProfilingCaseResponse.SerializeToString,
            ),
            'CancelProfilingCase': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelProfilingCase,
                    request_deserializer=profiling__pb2.CancelProfilingCaseRequest.FromString,
                    response_serializer=profiling__pb2.CancelProfilingCaseResponse.SerializeToString,
            ),
            'CloseProfilingSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseProfilingSession,
                    request_deserializer=profiling__pb2.CloseProfilingSessionRequest.FromString,
                    response_serializer=profiling__pb2.CloseProfilingSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edgeshard.profiling.v1.WorkerProfilingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edgeshard.profiling.v1.WorkerProfilingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerProfilingService:
    """---------------------------------------------------------------------------
    Services (§41, §49)
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def PrepareProfilingSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.profiling.v1.WorkerProfilingService/PrepareProfilingSession',
            profiling__pb2.PrepareProfilingSessionRequest.SerializeToString,
            profiling__pb2.PrepareProfilingSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunProfilingCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.profiling.v1.WorkerProfilingService/RunProfilingCase',
            profiling__pb2.RunProfilingCaseRequest.SerializeToString,
            profiling__pb2.RunProfilingCaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfilingCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.profiling.v1.WorkerProfilingService/GetProfilingCase',
            profiling__pb2.GetProfilingCaseRequest.SerializeToString,
            profiling__pb2.GetProfilingCaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelProfilingCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.profiling.v1.WorkerProfilingService/CancelProfilingCase',
            profiling__pb2.CancelProfilingCaseRequest.SerializeToString,
            profiling__pb2.CancelProfilingCaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseProfilingSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.profiling.v1.WorkerProfilingService/CloseProfilingSession',
            profiling__pb2.CloseProfilingSessionRequest.SerializeToString,
            profiling__pb2.CloseProfilingSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProfilingAdminServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartExperiment = channel.unary_unary(
                '/edgeshard.profiling.v1.ProfilingAdminService/StartExperiment',
                request_serializer=profiling__pb2.StartExperimentRequest.SerializeToString,
                response_deserializer=profiling__pb2.StartExperimentResponse.FromString,
                _registered_method=True)
        self.GetExperiment = channel.unary_unary(
                '/edgeshard.profiling.v1.ProfilingAdminService/GetExperiment',
                request_serializer=profiling__pb2.GetExperimentRequest.SerializeToString,
                response_deserializer=profiling__pb2.GetExperimentResponse.FromString,
                _registered_method=True)
        self.CancelExperiment = channel.unary_unary(
                '/edgeshard.profiling.v1.ProfilingAdminService/CancelExperiment',
                request_serializer=profiling__pb2.CancelExperimentRequest.SerializeToString,
                response_deserializer=profiling__pb2.CancelExperimentResponse.FromString,
                _registered_method=True)
        self.BuildProfileSnapshot = channel.unary_unary(
                '/edgeshard.profiling.v1.ProfilingAdminService/BuildProfileSnapshot',
                request_serializer=profiling__pb2.BuildProfileSnapshotRequest.SerializeToString,
                response_deserializer=profiling__pb2.BuildProfileSnapshotResponse.FromString,
                _registered_method=True)


class ProfilingAdminServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StartExperiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExperiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelExperiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildProfileSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfilingAdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.StartExperiment,
                    request_deserializer=profiling__pb2.StartExperimentRequest.FromString,
                    response_serializer=profiling__pb2.StartExperimentResponse.SerializeToString,
            ),
            'GetExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExperiment,
                    request_deserializer=profiling__pb2.GetExperimentRequest.FromString,
                    response_serializer=profiling__pb2.GetExperimentResponse.SerializeToString,
            ),
            'CancelExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelExperiment,
                    request_deserializer=profiling__pb2.CancelExperimentRequest.FromString,
                    response_serializer=profiling__pb2.CancelExperimentResponse.SerializeToString,
            ),
            'BuildProfileSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildProfileSnapshot,
                    request_deserializer=profiling__pb2.BuildProfileSnapshotRequest.FromString,
                    response_serializer=profiling__pb2.BuildProfileSnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edgeshard.profiling.v1.ProfilingAdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edgeshard.profiling.v1.ProfilingAdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProfilingAdminService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.profiling.v1.ProfilingAdminService/StartExperiment',
            profiling__pb2.StartExperimentRequest.SerializeToString,
            profiling__pb2.StartExperimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.profiling.v1.ProfilingAdminService/GetExperiment',
            profiling__pb2.GetExperimentRequest.SerializeToString,
            profiling__pb2.GetExperimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.profiling.v1.ProfilingAdminService/CancelExperiment',
            profiling__pb2.CancelExperimentRequest.SerializeToString,
            profiling__pb2.CancelExperimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildProfileSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edgeshard.profiling.v1.ProfilingAdminService/BuildProfileSnapshot',
            profiling__pb2.BuildProfileSnapshotRequest.SerializeToString,
            profiling__pb2.BuildProfileSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
